In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

/anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [3]:
df_data = pd.read_csv("adult.csv")

In [4]:
df_data.head()

age          workclass  fnlwgt   education  educational-num  \
0   39          State-gov   77516   Bachelors               13   
1   50   Self-emp-not-inc   83311   Bachelors               13   
2   38            Private  215646     HS-grad                9   
3   53            Private  234721        11th                7   
4   28            Private  338409   Bachelors               13   

        marital-status          occupation    relationship    race   gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [5]:
df_data.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [6]:
df_data["native-country"].value_counts().index[0]

' United-States'

In [7]:
df_data["income"].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [8]:
df_data = df_data.drop(['fnlwgt', 'educational-num'], axis = 1) 

In [9]:
col_names = df_data.columns

In [10]:
for c in col_names: 
    df_data = df_data.replace("?", np.NaN) 
df_data = df_data.apply(lambda x:x.fillna(x.value_counts().index[0]))

In [11]:
category_col =['workclass', 'education', 'marital-status', 'occupation', 'relationship', 
               'race', 'gender', 'native-country', 'income']  
labelEncoder = preprocessing.LabelEncoder() 
  
mapping_dict ={} 
for col in category_col: 
    df_data[col] = labelEncoder.fit_transform(df_data[col]) 
  
    le_name_mapping = dict(zip(labelEncoder.classes_, 
                        labelEncoder.transform(labelEncoder.classes_))) 
  
    mapping_dict[col]= le_name_mapping 
print(mapping_dict) 

{'education': {' 11th': 1, ' Masters': 12, ' Bachelors': 9, ' Assoc-acdm': 7, ' Prof-school': 14, ' 12th': 2, ' 1st-4th': 3, ' 7th-8th': 5, ' Assoc-voc': 8, ' HS-grad': 11, ' 9th': 6, ' Some-college': 15, ' Doctorate': 10, ' Preschool': 13, ' 10th': 0, ' 5th-6th': 4}, 'income': {' <=50K': 0, ' >50K': 1}, 'gender': {' Male': 1, ' Female': 0}, 'race': {' Black': 2, ' Other': 3, ' White': 4, ' Asian-Pac-Islander': 1, ' Amer-Indian-Eskimo': 0}, 'marital-status': {' Married-spouse-absent': 3, ' Never-married': 4, ' Separated': 5, ' Divorced': 0, ' Widowed': 6, ' Married-AF-spouse': 1, ' Married-civ-spouse': 2}, 'occupation': {' Tech-support': 13, ' Adm-clerical': 1, ' Armed-Forces': 2, ' Craft-repair': 3, ' Priv-house-serv': 9, ' ?': 0, ' Other-service': 8, ' Handlers-cleaners': 6, ' Farming-fishing': 5, ' Exec-managerial': 4, ' Machine-op-inspct': 7, ' Prof-specialty': 10, ' Protective-serv': 11, ' Transport-moving': 14, ' Sales': 12}, 'workclass': {' Self-emp-not-inc': 6, ' Local-gov': 2,

In [12]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
  
X = df_data.drop('income', axis = 1) 
Y = df_data['income']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100) 

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
dt_clf_gini = DecisionTreeClassifier(criterion = "gini", 
                                     random_state = 100, 
                                     max_depth = 5, 
                                     min_samples_leaf = 5) 
dt_clf_gini.fit(X_train, y_train) 

y_pred_gini = dt_clf_gini.predict(X_test)
print ("Desicion Tree using Gini Index\nAccuracy is ", accuracy_score(y_test, y_pred_gini)*100 )
confusion_matrix = confusion_matrix(y_test, y_pred_gini)
print (confusion_matrix)
print('\nAccuracy: ', dt_clf_gini.score(X_test, y_test)*100)
print('Precision: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[0,1].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('Recall: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[1,0].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('\n', classification_report(y_test, y_pred_gini))

Desicion Tree using Gini Index
Accuracy is  83.13031016480704
[[7017  411]
 [1237 1104]]

Accuracy:  83.13031016480704
Precision:  72.87128712871286
Recall:  47.15933361811192

               precision    recall  f1-score   support

           0       0.85      0.94      0.89      7428
           1       0.73      0.47      0.57      2341

   micro avg       0.83      0.83      0.83      9769
   macro avg       0.79      0.71      0.73      9769
weighted avg       0.82      0.83      0.82      9769



In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
rf_clf = RandomForestClassifier(random_state=0, n_estimators=100) 
rf_clf.fit(X_train, y_train) 

y_pred_rf = rf_clf.predict(X_test)
print ("Desicion Tree using Gini Index\nAccuracy is ", accuracy_score(y_test, y_pred_rf)*100 )
confusion_matrix = confusion_matrix(y_test, y_pred_rf)
print (confusion_matrix)
print('\nAccuracy: ', rf_clf.score(X_test, y_test)*100)
print('Precision: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[0,1].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('Recall: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[1,0].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('\n', classification_report(y_test, y_pred_rf))

Desicion Tree using Gini Index
Accuracy is  85.1366567714198
[[6866  562]
 [ 890 1451]]

Accuracy:  85.1366567714198
Precision:  72.08147044212619
Recall:  61.98205894916702

               precision    recall  f1-score   support

           0       0.89      0.92      0.90      7428
           1       0.72      0.62      0.67      2341

   micro avg       0.85      0.85      0.85      9769
   macro avg       0.80      0.77      0.79      9769
weighted avg       0.85      0.85      0.85      9769



In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
lr_clf = LogisticRegression() 
lr_clf.fit(X_train, y_train) 

y_pred_lr = lr_clf.predict(X_test) 
print ("Logistic Regression Accuracy is ", accuracy_score(y_test, y_pred_lr)*100 )
confusion_matrix = confusion_matrix(y_test, y_pred_lr)
print (confusion_matrix)
print('\nAccuracy: ', lr_clf.score(X_test, y_test)*100)
print('Precision: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[0,1].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('Recall: ', confusion_matrix[1,1].astype(float)/(confusion_matrix[1,0].astype(float)+confusion_matrix[1,1].astype(float))*100)
print('\n', classification_report(y_test, y_pred_lr))

/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Logistic Regression Accuracy is  80.42788412324701
[[7156  272]
 [1640  701]]

Accuracy:  80.42788412324701
Precision:  72.04522096608427
Recall:  29.944468175993165

               precision    recall  f1-score   support

           0       0.81      0.96      0.88      7428
           1       0.72      0.30      0.42      2341

   micro avg       0.80      0.80      0.80      9769
   macro avg       0.77      0.63      0.65      9769
weighted avg       0.79      0.80      0.77      9769

